### ISSUE TITLE
PyPDF2.utils.PdfReadError: Could not find object.

### ISSUE THREAD

**Issue by gonultasbu** [gonultasbu/pdf_merge#1]
On some PDF files the program gives the following error:
```
PdfReadWarning: Object 225 0 not defined. [pdf.py:1629]
Traceback (most recent call last):
  File "/home/mert/Desktop/pdf_merge/pdf_merge.py", line 30, in <module>
    merger.write(fout)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/merger.py", line 230, in write
    self.output.write(fileobj)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/home/mert/anaconda3/envs/pdf_merge/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1631, in getObject
    raise utils.PdfReadError("Could not find object.")
PyPDF2.utils.PdfReadError: Could not find object.

Process finished with exit code 1
```
Example PDF given in the attachment.

[textDetection.pdf](https://github.com/gonultasbu/pdf_merge/files/2453712/textDetection.pdf)

**Comment by gonultasbu** [comment]
Solution:

https://stackoverflow.com/a/52687771/10405090

**Comment by pavel167** [comment]
Still not working after applying the solution:
```
PdfReadWarning: Object 0 0 not defined. [pdf.py:1635]

Traceback (most recent call last):
  File "/home/pavel/python_code/explore_one_file_Amazon3.py", line 32, in find_isbn
    pdfWriter.write(fout)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 577, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 553, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 577, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 553, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 562, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 577, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 553, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 562, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 592, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 553, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 592, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 553, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 592, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 553, in _sweepIndirectReferences
```
........ then huge number of alternation of lines, containing "line 553" and "line 592"
........ here is the end part:
```
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 592, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 553, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 583, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 1599, in getObject
    retval = self._getObjectFromStream(indirectReference)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py", line 1573, in _getObjectFromStream
    obj = readObject(streamData, self)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/generic.py", line 579, in readFromStream
    value = readObject(stream, pdf)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/generic.py", line 71, in readObject
    return ArrayObject.readFromStream(stream, pdf)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/generic.py", line 166, in readFromStream
    arr.append(readObject(stream, pdf))
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/generic.py", line 98, in readObject
    return NumberObject.readFromStream(stream)
  File "/usr/local/lib/python3.6/dist-packages/PyPDF2/generic.py", line 273, in readFromStream
    return NumberObject(num)
RecursionError: maximum recursion depth exceeded
```
